scrape_configs:
- job_name: cadvisor
  scrape_interval: 15s
  static_configs:
  - targets: ['cadvisor:8080']
    labels:
      group: 'docker'
  - targets: ['10.1.1.17:8080']
    labels:
      group: 'graylog'
